version: "3.4"
services:
  editor:
    image: dtlfair/metadata-editor:2.1
    container_name: editor
    ports:
      - "8001:80"
    restart: unless-stopped
    volumes:
      - ./data/editor/config:/usr/share/nginx/html/conf
  
  fairifier:
    image: dtlfair/fairifier
    container_name: fairifier
    ports:
      - "8002:3333"
    depends_on:
      - virtuoso
    restart: unless-stopped
    volumes:
      - ./data/fairifier/data:/fairifier_data
      - ./data/fairifier/config:/configuration

  fdp:
    image: fairdata/fairdatapoint:1.0.0
    container_name: fdp
    ports:
      - "8003:80"
    depends_on:
      - agraph
    restart: unless-stopped

  search:
    image: dtlfair/search:develop
    container_name: search
    ports:
      - "8004:80"
      - "8084:8080"
      - "9200:9200"
    environment:
      - "ES_URL=http://localhost/searchserver"
    restart: unless-stopped

  virtuoso:
    image: tenforce/virtuoso
    container_name: virtuoso
    ports:
      - "8890:8890"
    restart: unless-stopped

  agraph:
    image: franzinc/agraph:v6.1.1
    container_name: agraph
    ports:
      - "10035:10035"
    restart: unless-stopped

  fdpclient:
    image: fairdata/fairdatapoint-client:1.0.0
    container_name: fdpclient
    restart: unless-stopped
    ports:
      - 8005:80
    environment:
      - FDP_HOST=fdp

  mongo:
    image: mongo:4.0.12
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
        - ./data/mongo:/data/db
    command: mongod